app/models.py
from app import db

class JsonModel(object):
    def as_dict(self):
       return {c.name: getattr(self, c.name) for c in self.__table__.columns}

class Categories_Lookup(db.Model,JsonModel):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(30), index=True, unique=True, nullable=False)
    favorites = db.relationship('Favorite', backref='Category', lazy='dynamic')
    cteated_date = db.Column(db.DateTime,nullable=False)
    modified_date = db.Column(db.DateTime,nullable=False)

class Favorite(db.Model,JsonModel):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(30), index=True, nullable=False)
    description = db.Column(db.Text)
    ranking = db.Column(db.Integer,nullable=False)
    cteated_date = db.Column(db.DateTime,nullable=False)
    modified_date = db.Column(db.DateTime,nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('categories__lookup.id'),nullable=False)
    meta_data = db.relationship('Meta_Data', backref='FavoriteItem', lazy='dynamic')

class Meta_Data(db.Model,JsonModel):
    id= db.Column(db.Integer, primary_key=True)
    key=db.Column(db.String(30), index=True, nullable=False)
    value=db.Column(db.String(30), index=True, nullable=False)
    favorite_id=db.Column(db.Integer, db.ForeignKey('favorite.id'),nullable=False)

class Audit_Log(db.Model,JsonModel):
    id = db.Column(db.Integer, primary_key=True)
    log_date = db.Column(db.DateTime,nullable=False)
    description = db.Column(db.Text,nullable=False)

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)
app.config.from_object(Config)

db = SQLAlchemy(app)
migrate = Migrate(app, db)

from app import models, errors
from app.main.routes import main_blueprint
from app.API.categories import categories_blueprint
from app.API.favorites import favorites_blueprint
from app.API.metadata import metadata_blueprint
from app.API.logs import logs_blueprint

# register blueprints
for blueprint in (categories_blueprint, favorites_blueprint,metadata_blueprint,logs_blueprint,main_blueprint):
    app.register_blueprint(blueprint)

app/main/routes.py
from flask import render_template, Blueprint, url_for
from app.API.categories import GetAllCategories

main_blueprint = Blueprint('main', __name__,template_folder='templates')

@main_blueprint.route('/')
@main_blueprint.route('/index')
def index():
    return render_template("main/index.html",title="Home")

@main_blueprint.route('/logs')
def logs():
    return render_template("main/logs.html",title="Audit Logs")

@main_blueprint.route('/favorites')
def favorites():
    objResponse = GetAllCategories()
    return render_template("main/favorites.html",title="Favorite List", lstCategories = objResponse.json["data"])

app/routes.py
from app import app, db
from flask import render_template, jsonify
from Util import failure
from app.API.categories import GetAllCategories

@app.route('/')
@app.route('/index')
def index():
    return render_template("index.html",title="Home")

@app.route('/logs')
def logs():
    return render_template("logs.html",title="Audit Logs")

@app.route('/favorites')
def favorites():
    objResponse = GetAllCategories()
    return render_template("favorites.html",title="Favorite List", lstCategories = objResponse.json["data"])

app/templates/_card.html
<div class="card" id={{category.id}}>
    <div class="row">
        <div class="card_title col-md-2">
            <p style="margin:0px">{{category.title|title}}</p>
        </div>
        <div class="col-md-10">
            <a data-toggle="collapse" data-target="#collapse_favorites_{{category.id}}" title="Show / Hide Items"
            class="card-controls"><i class="fas fa-compress"></i></a>
            <a title="Delete Category" class="btnDeleteCat card-controls"><i class="far fa-trash-alt"></i></a>
            <i id = "icnLoading_{{category.id}}" class="card-controls fas fa-spinner fa-spin" style="float: right ;display: none;" ></i>
        </div>
    </div>
</div>

app/templates/_favoritesModals.html
<!-- Add Category Modal -->
<div class="modal fade" id="addCategoryModal" tabindex="-1" role="dialog" aria-labelledby="addCategoryModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addCategoryModalLabel">Add New Category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="categoryForm" action="/AddCategory" method="post" class="needs-validation" novalidate>
                    <div class="form-group">
                        <label for="strCategoryTitle">Category Title</label>
                        <input type="text" class="form-control" name="strCategoryTitle" id="strCategoryTitle" required>
                        <div class="invalid-feedback">
                            This Field is Required.
                        </div>
                    </div>
                    <button type="submit" class="fav-btn btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Meta Data Modal -->
<div class="modal fade" id="metaData" tabindex="-1" role="dialog" aria-labelledby="MetaDataLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="MetaDataLabel">Meta Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="favTable collapse show">
                            <div id="metaDataGrid"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/_footer.html
<div class="container-fluid footer">
    <div class="row">
        <div class="col-md-12">
            <a href="https://github.com/a-maksousa" target="_blank">
                <img style="float: right;width: 60px" src="{{url_for('static',filename='images/Github.png')}}">
            </a>
            <a href="https://www.linkedin.com/in/amaksousa/" target="_blank">
                <img style="float: right;width: 60px" src="{{url_for('static',filename='images/linkedin.png')}}">
            </a>
        </div>
    </div>
</div>

app/templates/_header.html
<!-- logo navbar -->
<nav class=" navbar navbar-default">
    <div class="container-fluid">
        <div class="row">
            <div class="navbar-header col-md-2">
                <a class="navbar-brand" href="{{url_for('main.index')}}">
                    <img style="width: 110px" src="{{url_for('static',filename='images/Logo.png')}}">
                </a>
            </div>
        </div>
    </div>
</nav>

<!-- screen path navbar -->
{% if title != "Home" %}
<div class="page_header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <a class="page_header_label" href="{{url_for('main.index')}}">
                    <h6 class="page_header_item">Home</h6>
                </a>
                <i style="vertical-align: sub" class="page_header_item fas fa-caret-right"></i>
                <h6 class="page_header_item">{{ title }}</h6>
            </div>
        </div>
    </div>
</div>
{% endif %}

app/templates/base.html
<html>

<head>
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/Favorites.png') }}">

    <!-- styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/all.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.toast.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery-ui.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/jsgrid.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/jsgrid-theme.min.css') }}">

    <!-- scripts -->
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/datatables.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.toast.js') }}"></script>
    <script src="{{ url_for('static', filename='js/all.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery-ui.js') }}"></script>
    <script src="{{ url_for('static', filename='js/sweetalert2@8.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jsgrid.min.js') }}"></script>

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Favorite Things</title>
    {% endif %}

</head>

<body>

    <!-- header -->
    {% include "_header.html" %}

    <!-- child template -->
    {% block content %}{% endblock %}

    <!-- footer -->
    {% include "_footer.html" %}

</body>

<!-- loading screen -->
<div class="preloader">
    <div class="status-mes">
        <div class="bigSqr">
            <div class="square first"></div>
            <div class="square second"></div>
            <div class="square third"></div>
            <div class="square fourth"></div>
        </div>
        <div class="text_loading text-center bold">Loading</div>
    </div>
</div>

</html>

app/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class=container>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="cat_card col-md-3">
            <a href="{{url_for('logs')}}"><img class="cat_logo"
                    src="{{url_for('static',filename='images/Audit_Log.png')}}"></a>
            <h4>Audit Log</h4>
        </div>
        <div class="col-md-1"></div>
        <div class="cat_card col-md-3">
            <a href="{{url_for('favorites')}}"><img class="cat_logo"
                    src="{{url_for('static',filename='images/Favorites.png')}}"></a>
            <h4>Favorite List</h4>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

app/templates/main/favorites.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <button type="button" class="fav-btn btn btn-primary" data-toggle="modal" data-target="#addCategoryModal">New
        Category</button>

    <div class="elementsContainer">
        {% for category in lstCategories %}
        <div class="row">
            <div class="col-md-12">
                {% include "_card.html" %}
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div id="collapse_favorites_{{category.id}}" class="favTable collapse show">
                    <div id="favorites_{{category.id}}"></div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% for category in lstCategories %}
    <script>
        InitFavGrid("{{category.id}}")
    </script>
    {% endfor %}


</div>

{% include "_favoritesModals.html" %}

{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}
{% block content %}
<div class=container>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="cat_card col-md-3">
            <a href="{{url_for('main.logs')}}"><img class="cat_logo"
                    src="{{url_for('static',filename='images/Audit_Log.png')}}"></a>
            <h4>Audit Log</h4>
        </div>
        <div class="col-md-1"></div>
        <div class="cat_card col-md-3">
            <a href="{{url_for('main.favorites')}}"><img class="cat_logo"
                    src="{{url_for('static',filename='images/Favorites.png')}}"></a>
            <h4>Favorite List</h4>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

app/templates/main/logs.html
{% extends "base.html" %}
{% block content %}
<div class="container">
        <button type="button" id=btnClearLogs class="fav-btn btn btn-primary">Clear Logs</button>
    <div class="elementsContainer">
        <div class="row">
            <div class="col-md-12">
                <div class="favTable">
                    <div id="tblLogs"></div>
                </div>
            </div>
        </div>
    </div>
    <script>
        InitLogsGrid()
    </script>
</div>
{% endblock %}